### ISSUE TITLE
Premium Edition

### ISSUE THREAD

**Issue by rrbadam** [BerryWorksSoftware/edi-json#1]
Any update on premium edition

**Comment by dmat** [comment]
I'm interested in the premium edition, any update?

**Comment by canabrook** [comment]
I just responded to a query from what I think is your own email address. If
you haven’t received my replay, please contact me at scott@canabrook.org and
I can give you all the details on the premium edition of the EDI to JSON
tool.

Scott Mayberry
Berryworks Software


On November 13, 2018 at 12:23:29 PM, dmat (notifications@github.com) wrote:

I'm interested in the premium edition, any update?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BerryWorksSoftware/edi-json/issues/1#issuecomment-438382211>,
or mute the thread

**Comment by Jelenbl** [comment]
Interested in premium as well - Also, is there way to reverse the process, JSON->EDI?

**Comment by canabrook** [comment]
Note that the Premium Edition is fully available, including support for JSON to EDI.  See the updated README.md.
