### ISSUE TITLE
is API available?

### ISSUE THREAD

**Issue by bobsov** [BerryWorksSoftware/edi-json#2]
I have a need to convert 837 to json. Is there premium edition out there that we can subscribe and start using?

**Comment by canabrook** [comment]
Yes. It is not available via GitHub, but there is a complete Premium
Edition available for licensing. It is in production in one large-scale
production system — handling 837 health care claims — and is in evaluation
for several others. It is usable in both a command line tool and as a Java
API.

A no-obligation evaluation agreement can be arranged with companies
considering the purchase of a license.

Please let me know if you have questions, technical or otherwise, and feel
free to use this, my direct email address scott@canabrook.org .

By the way, I am completing a JSON to EDI companion that performs the
reverse transformation, taking JSON as input and producing EDI output.

Regards,
Scott Mayberry
BerryWorks Software
Nashville, TN


On February 11, 2019 at 4:28:47 PM, bobsov (notifications@github.com) wrote:

I have a need to convert 837 to json. Is there premium edition out there
that we can subscribe and start using?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BerryWorksSoftware/edi-json/issues/2>, or mute the
thread
