### ISSUE TITLE
Can I parse a 271 file into json?

### ISSUE THREAD

**Issue by harriettxing** [BerryWorksSoftware/edi-json#4]
Hi,

I am looking for a tool that can parse a 271 (insurance eligibility) file into either json or xml.  

I tried using berryworks as following, but got an error.  

$ java -jar edireader-json-basic-5.5.13.jar 271Sample2 a.out

Could not find queued element loop for putAttribute()
$ 

Am I running it correctly?  Thanks.

**Comment by canabrook** [comment]
Yes, I think you are using it correctly. This is apparently a bug in the
handling of the 271. I have several 271 samples and will see if I can
reproduce the issue. If you have a sample that is safe to share (for
privacy purposes) that would be great. I know the core X12 parser handles
271s just fine, but this probably has to do with the rendering as JSON.

Are you using version 5010 of the 271?

Scott Mayberry
BerryWorks Software
Nashville, TN



On July 12, 2019 at 1:23:16 PM, harriettxing (notifications@github.com)
wrote:

Hi,

I am looking for a tool that can parse a 271 (insurance eligibility) file
into either json or xml.

I tried using berryworks as following, but got an error.

$ java -jar edireader-json-basic-5.5.13.jar 271Sample2 a.out

Could not find queued element loop for putAttribute()
$

Am I running it correctly? Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/BerryWorksSoftware/edi-json/issues/4?email_source=notifications&email_token=ABQDKPFAJATUNO7O4HFDN7TP7DDZJA5CNFSM4ICOZ4F2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G66EQFA>,
or mute the thread

**Comment by harriettxing** [comment]
[271Sample.txt](https://github.com/BerryWorksSoftware/edi-json/files/3387587/271Sample.txt)

Sample 271 attached.

**Comment by canabrook** [comment]
I have resolved the issue with the 271. I am attaching two JSON output
files for your 271 sample. One with the additional descriptive annotations,
and one without. Both are formatted with line breaks and indenting spaces,
but that is optional too.

I have not pushed out a new build of the free version yet, but need to do
that soon.

Scott




On July 12, 2019 at 1:32:11 PM, harriettxing (notifications@github.com)
wrote:

271Sample.txt
<https://github.com/BerryWorksSoftware/edi-json/files/3387587/271Sample.txt>

Sample 271 attached.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/BerryWorksSoftware/edi-json/issues/4?email_source=notifications&email_token=ABQDKPFGEYXKJSRN3NUXIEDP7DE2VA5CNFSM4ICOZ4F2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZ2RAPA#issuecomment-510988348>,
or mute the thread

**Comment by canabrook** [comment]
The 5.5.14 release includes the fixes for the 271.
